port: 3000

gitlabBaseURL: 'http://gitlab.atg.digital/api/v4'
gitlabProjectId: 1
gitlabAccessToken: ''

JIRAAPIBaseURL: ''
JIRAWebBaseURL: ''
JIRAAPIToken: ''
JIRAUser: ''

togglBaseURL: 'https://www.toggl.com/api/v8/'
togglAPIToken: ''

redisSessionStore:
  host: 'localhost'
  port: 6379
  db: 1